app:
  name: "web_app"
  mode: "dev"
  port: 8084
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "suxianjin"
  dbname: "sql_demo"
redis:
  host: "127.0.0.1"
  port: 6377
  password: "suxianjin123"
  db: 0
  pool_size: 20

snowflake:
  starttime: "2020-07-01"
  machineID: 1
